In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr_zero = np.zeros(10,)

In [6]:
arr_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr_zero = np.zeros(10,5)

TypeError: Cannot interpret '5' as a data type

In [8]:
arr_zero = np.zeros((2,10))

In [9]:
arr_zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr_zero = np.zeros((2,10,2))

In [11]:
arr_zero

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
arr_zero = np.zeros(10,)


In [13]:
arr_zero[4]= 1

In [14]:
arr_zero

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
range_vector = np.arange(10,50)

In [16]:
range_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
arr = np.arange(10)

In [18]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np.ranshape