# Numpy

In [1]:
import numpy as np

## 1-d array

In [2]:
one_dim_array = np.array([1,2,3,4,5])

In [3]:
one_dim_array.shape

(5,)

In [4]:
one_dim_array[0]

1

In [5]:
type(one_dim_array)

numpy.ndarray

### np.arange - creating arrays at specific range (similar to Python range() function)

In [6]:
arr1 = np.arange(10)

In [7]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = np.arange(20,30)

In [9]:
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

### math operations

In [12]:
sample_arr = np.arange(1, 6)
sample_arr

array([1, 2, 3, 4, 5])

In [13]:
# Multiplication
sample_arr * 5

array([ 5, 10, 15, 20, 25])

In [14]:
# division
sample_arr / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

### indexing

In [15]:
sample_arr2 = np.arange(1, 6)
sample_arr2

array([1, 2, 3, 4, 5])

In [18]:
# get [2,3,4]
sample_arr2[1:-1]

array([2, 3, 4])

In [20]:
sample_arr2 % 2 == 0

array([False,  True, False,  True, False])

In [21]:
sample_arr2[sample_arr2 % 2 == 0]

array([2, 4])

## 2-D array

In [26]:
a_two_dim_arr = np.array([[2, 2], [2, 2]])

In [27]:
a_two_dim_arr.shape

(2, 2)

In [28]:
a_two_dim_arr

array([[2, 2],
       [2, 2]])

In [29]:
# With arange, create a 4 * 4 array (0 to 16)
four_by_four = np.arange(0, 16)
four_by_four

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
four_by_four = four_by_four.reshape(4, 4) # divide all the array items into rows and columns
four_by_four

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### indexing

In [32]:
# get the first row
four_by_four[0]

array([0, 1, 2, 3])

In [33]:
# get the last row
four_by_four[-1]

array([12, 13, 14, 15])

In [35]:
# get the first column
four_by_four[:, 0]

array([ 0,  4,  8, 12])

In [36]:
# get the last column
four_by_four[:, -1]

array([ 3,  7, 11, 15])

In [37]:
# get 5, 6, 9, 10
four_by_four[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])